### ISSUE TITLE
add_MARBL (compute): investigate noise in vanishing layer

### ISSUE THREAD

**Issue by mnlevy1981** [mnlevy1981/MOM6#41]
https://github.com/marbl-ecosys/MARBL/pull/381 added support for `bot_flux_to_tend` and helped prevent DIC from going off the rails in the vanishing layers, but closer inspection found there was still noise in `O2`:

![O2 with bot_flux_to_tend](https://user-images.githubusercontent.com/4297161/131545101-cfeafc7d-4fba-4162-bd36-c66dd8fca79c.png)

That led to https://github.com/marbl-ecosys/MARBL/pull/386 where a few bugs were found and fixed (`dzr_loc` was still being used in `sed_denitrif` and `other_remin`) but there are still some columns with noise in the vanishing layers

**Comment by mnlevy1981** [comment]
Currently we are investigating column indexed by `i=85`, `j=317` in languages that count from 1 (`i=84`, `j=316` for languages that count from 0). In that column, `DIC` looks like

![DIC_fullcol](https://user-images.githubusercontent.com/4297161/131552423-a6f454ce-1dd8-4e03-a372-c39045d645c7.png)

Zooming in on the bottom 10 cm, the difference between the two looks like

![DIC_fulltend_BBL](https://user-images.githubusercontent.com/4297161/131552480-e5fe1654-5979-4dc7-b42f-2de073690188.png)

We've looked at four potential sources of this spike the numbers don't add up.

* The MARBL source/sink term (`J_DIC`):

![DIC_MARBL_tend](https://user-images.githubusercontent.com/4297161/131552616-e575abae-a357-4fb9-9955-8e007e806cf4.png)

* The contribution from calling `tracer_vertdiff()`:

![DIC_vertdiff_tend](https://user-images.githubusercontent.com/4297161/131552673-fc5f84d6-c6ba-4311-abab-29c8686f1f20.png)

* `DIC_lbdxy_conc_tendency`:

![DIC_lbdxy_conc_tendency](https://user-images.githubusercontent.com/4297161/131552727-12df955c-b754-4620-afef-ae68f09a1931.png)

* `DIC_dfxy_conc_tendency`:

![DIC_dfxy_conc_tendency](https://user-images.githubusercontent.com/4297161/131552754-907bfd23-196d-46c3-83e6-e107a0070d58.png)

All four of those contributing terms have been scaled by 3600.

**Comment by ashao** [comment]
One of my suggestions would be to look at the tracer 'content' tendencies (i.e. concentration*h) since that's what the model is actually conserving and it's somewhat ambiguous what the 'correct' layer thickness would be to get the same result (i.e. should you use 'h' from before or after the process happened, or maybe a time average). For all the transport-related tendencies' you want:
- `id_trxh_tendency`: The total time tendency of tracer content
- `id_adv_xy`: Tracer content change due to convergence of advective fluxes
- `id_adv_remap_cont`: Tracer content change from the vertical remapping
- `id_dfxy_cont`: Tracer content change from convergence of neutral diffusion

You'll note here that the lateral boundary diffusion and vertical diffusion tendencies are missing. The former should be 0. assuming your mixed layer isn't full column depth, whereas we have no generic diagnostic for that, but we could add one.

**Comment by mnlevy1981** [comment]
Okay, the tools I've been using aren't the greatest but I _think_ it's fair to say that the advective fluxes are introducing this spike. Keith and I verified that `DICh_tendency[t=1] = (DIC[t=1]*h[t=1] - DIC[t=0]*h[t=0])/dt`, so I've been looking at time level 1 (hence a slight shift in the vertical coordinates).

Here's `DICh_tendency` (the `id_trxh_tendency` term), which shows a similar spike in the upper levels of the vanishingly thin layers as the `DIC[t=1] - DIC[t=0]` plot in the previous comment:

![DICh_tendency](https://user-images.githubusercontent.com/4297161/131575939-1464b440-d259-4e84-99c0-2cd3943ca906.png)

Of all the other three terms, only `DIC_advection_xy` (the `id_adv_xy` contribution) shows a similar spike:

![DIC_advection_xy](https://user-images.githubusercontent.com/4297161/131576021-ee2ac7b0-3b2b-4744-9590-97d367a6be09.png)

The other two plots are basically vertical at 0. It does not seem like `id_trxh_tendency = id_adv_xy + id_adv_remap_cont + id_dfxy_cont` when comparing at the same time level, but the pattern of `DIC_advection_xy`above is sufficient to make me think that is the term to investigate first.

**Comment by mnlevy1981** [comment]
closing this, I think we understand the phenomenon (advection is inflating layers that had previously been vanishingly thin)
