### ISSUE TITLE
add_MARBL (future): support for NDEP coming from atm component

### ISSUE THREAD

**Issue by mnlevy1981** [mnlevy1981/MOM6#65]
Mariana is working on a CESM feature where NDEP would be passed to the ocean model via the coupler rather than being read from a file (I think CAM would compute it in most cases, but datm and some CAM simple models would read it from disk) -- this would ensure consistency between the land and ocean models, and perhaps save me the effort of reading ndep via share stream.

Currently, my branch supports reading an NDEP climatology but not the forcing needed for a transient run.

**Comment by klindsay28** [comment]
@mvertens has added support for datm to pass ndep in https://github.com/ESCOMP/CDEPS/pull/158
However, it's not clear if this has been vetted in any G-type compset.

**Comment by mvertens** [comment]
@klindsay28 - the component caps have not been modified yet to accept the ndep passed from datm. This was just the first step. The next step is to have CAM updated so that it can read in ndep the same way datm does. At that point we can start removing the code from the components themselves that read in ndep from within their code base.

**Comment by mnlevy1981** [comment]
It took some work in CDEPS ([`69e55021`](https://github.com/ESCOMP/CDEPS/tree/69e550218bb722372162965d2ab3d26ea2a6e3d6)) and CMEPS ([`b31366f`](https://github.com/ESCOMP/CMEPS/tree/b31366feb9e8baf87262e59ab686dbf13d2923c4)) as well, but as of 3d8e164, this is complete. (It got moved to from the "future" task list to the "do now" task list when we realized addressing it was part of #69)
